### PR TITLE
feat: nix-based system extensions

### PR DESCRIPTION
**Pull request by tulilirockz**
This PR implements #3!

Missing things:

- [x] RPM Package + automount service
- [x] Decouple `config.json` from nix flake by using bash shenanigans
- [x] Logging for most of the application
- [x] Deattach the "bake-recipe" build off of the flake just so that we dont need to use --impure for any other operation
- [x] Layer build command without nix (shell script for building it, or even using something like guix instead of nix)
- [x] Layered nix store for build cache
- [x] Actual proper utility for managing `config.json` and other files since just is super annoying to use around that (maybe written in Go or something)
- [x] Fixing the permission issues on `/usr/*`
- [x] Systemd-confext support
- [X] SELinux compatibility ([upstream issue](https://github.com/NixOS/nixpkgs/issues/252620))
- [x] Nix stores on `/usr/store` + bind-mount to `/nix` for nix compatibility

~Here is a graph explaining what this PR does~ - Graph was outdated after some changes, Ill update once everything is done

### CODE REVIEW

**Comment by tulilirockz** [comment]
I just found out why I had so many permission issues on `/usr`... Apparently this SquashFS approach does not conserve the SELinux in `/usr/{lib,bin,share,}`, so programs just break. At first we should just disable SELinux, but we do need to fix that at some point.

**Comment by tulilirockz** [comment]
Sorry for all the `Just` commits, the justfile is super annoying to mess around with!

**Comment by KyleGospo** [comment]
Since this is writeable, can you simply restorecon -R post mount?

**Comment by tulilirockz** [comment]
Sadly that doesn't work :( If you try to do that it just doesn't work and complains about the `read-only filesystem` thing, since the overlay itself after applying is not writeable

**Comment by tulilirockz** [comment]
The overlay itself is not writeable

**Comment by tulilirockz** [comment]
Well, the initial scope for this project is almost done! The only thing actually missing is some misc bugs and better system integration, other than that it should be completely fine!

**Comment by tulilirockz** [comment]
We moved this pull request to https://github.com/ublue-os/bext !

**Pull request closed without merging**
